version: '3.1'

services:
  db:
    container_name: user-service-pgdb
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .dev.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

volumes:
  pgdata: